version: '3.8'

services:
  frontend:
    image: shivamjswl/frontend:latest
    ports:
      - "3000:5173"
    restart: unless-stopped
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: shivamjswl/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # optional: only if you want MongoDB on manager node

volumes:
  mongo-data:
